# Generated by Django 3.2.12 on 2022-03-02 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('nb', 'Non-binary'), ('tr', 'Transgender'), ('in', 'Intersex'), ('ns', 'I prefer not to say')], max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^01[01679]-?\\d{3,4}-?\\d{4}$')]),
        ),
    ]
